name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main" ]   # đổi nếu bạn dùng nhánh khác

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps for upload
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Upload folder to HF Space via API (no git push)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - << 'PY'
          import os
          from huggingface_hub import upload_folder
          upload_folder(
              repo_id="tamcisco/hai-quan-chatbot",
              repo_type="space",
              folder_path=".",          # đẩy toàn bộ repo hiện tại
              path_in_repo=".",         # vào root của Space
              token=os.environ["HF_TOKEN"],
              commit_message="sync from GitHub Actions"
          )
          PY

